name: Experimental workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print environment
        run: |
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Hello from pogopin!"
      - name: Experimental step
        run: echo "This workflow was triggered by gh CLI."
